apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mqg3avn4n-python 
  janus-idp.io/tekton: mqg3avn4n-python
  backstage.io/kubernetes-id: mqg3avn4n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqg3avn4n-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  