apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mqg3avn4n-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:482c8e2c6e078bd5710739dc414a71b2a353725f@sha256:8a733b928b7edd3cc17f03ba83fe4d721b7f13224bfd729fa6e99852896f12d2
          name: container-image
