apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mqg3avn4n-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqg3avn4n-python 
  name: mqg3avn4n-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mqg3avn4n-python 
